### ISSUE TITLE
Can't build jar

### ISSUE THREAD

**Issue by comendantmc** [nopjmp/Dionysus#21]
**Describe the bug**
Some script are not found while trying to build a jar (decompile.sh for instance). I tried to use decompile.sh from other paper forks, but without success.

**To Reproduce**
```bash
git clone https://github.com/nopjmp/Dionysus.git
cd Dionysus
./dionysus jar
```

```bash
> java -version
openjdk version "1.8.0_332"
OpenJDK Runtime Environment (build 1.8.0_332-b03)
OpenJDK 64-Bit Server VM (build 25.332-b03, mixed mode)
```

```bash
> mvn -version
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Maven home: /opt/maven
Java version: 1.8.0_332, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-8-openjdk/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.16.12-arch1-1", arch: "amd64", family: "unix"
```

Build with openjdk 17 failed at even earlier stage.

**Misc**
Full command output https://paste.md-5.net/ikimufiwow

**Comment by comendantmc** [comment]
nvm, I switched to another java 8 compatible jdk and it works again. with openjdk it doesn't for some reason

**Comment by nopjmp** [comment]
It requires some things not included in distro openjdks unfortunately. I
was working on moving it to the newer solution for forks but lost
interest and time.

On March 8, 2022, GitHub Notifications ***@***.***> wrote:
> nvm, I switched to another java 8 compatible jdk and it works again.
> with openjdk it doesn't for some reason
>

—
Reply to this email directly, view it on GitHub
<https://github.com/nopjmp/Dionysus/issues/21#issuecomment-1062222787>,
or unsubscribe <https://github.com/notifications/unsubscribe-
auth/ABHSAGO6S7VHFYMFIJTNRILU67AAHANCNFSM5QHPYJYQ>.
You are receiving this because you are subscribed to this thread.Message
ID: ***@***.***>
