### ISSUE TITLE
Light optimisation

### ISSUE THREAD

**Issue by dG9hc3Q** [nopjmp/Dionysus#3]
**Is your feature request related to a problem? Please describe.**
Lag caused by light updates

**Describe the solution you'd like**
Queue light updates, like ccSpigot

**Describe alternatives you've considered**
ccSpigot

**Comment by nopjmp** [comment]
queue lighting updates is a default paper feature, but I need to expand it a bit more and optimize the lighting calculations with some modifications from phosphor / tuinity's light system. Main issue is that newer versions of minecraft are using VoxelShape obstractions and I need to study both sides and compare since I'm not familiar enough.

`queue-light-updates: true` in paper.yml

**Comment by dG9hc3Q** [comment]
Implemented as `light-updates-max-ms-per-tick`
